trigger:
  - main

parameters:
  - name: testSuite
    displayName: 'Select Test Suite to Run'
    type: string
    default: 'All'
    values:
      - 'All'
      - 'TypeScript'
      - 'JS_Single'
      - 'JS_Parallel'

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npx playwright install chromium --with-deps
    displayName: 'Install Playwright Browser'

  # 1. Run TypeScript Tests
  - script: npx playwright test --config=Playwright-TS/Playwright-TS/
    displayName: 'Run Playwright TS Tests'
    condition: or(eq('${{ parameters.testSuite }}', 'TypeScript'), eq('${{ parameters.testSuite }}', 'All'))
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  # 2. Run JavaScript Single Test
  - script: npm run test:js
    displayName: 'Run Playwright JS Single Test'
    condition: or(eq('${{ parameters.testSuite }}', 'JS_Single'), eq('${{ parameters.testSuite }}', 'All'))
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  # 3. Run JavaScript Parallel Tests
  - script: npm run test:js-parallel
    displayName: 'Run Playwright JS Parallel Tests'
    condition: or(eq('${{ parameters.testSuite }}', 'JS_Parallel'), eq('${{ parameters.testSuite }}', 'All'))
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  # Publish Results
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-results/*.xml'
      testRunTitle: 'Playwright Combined Results'
