trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npx playwright install chromium --with-deps
    displayName: 'Install Playwright Browser'

  # 1. Run Playwright Tests TS 
  - script: npx playwright test --config=Playwright-TS/Playwright-TS/
    displayName: 'Run Playwright TS Tests'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)
      
# 2. Run JavaScript Single Test
  - script: npm run test:js
    displayName: 'Run Playwright JS Single Test'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  - script: npm run test:js-parallel
    displayName: 'Run Playwright JS Parallel Tests'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  # 2. PHASE 2: JMETER PERFORMANCE TESTING
  - powershell: |
      choco install jmeter -y
      # Refresh environment path for current session
      $env:Path += ";$env:JMETER_PATH"
      jmeter -version
    displayName: 'Install and Verify JMeter'

  - powershell: |
      # Create report directory in the Binaries folder to prevent 'not found' errors
      New-Item -ItemType Directory -Force -Path $(Build.BinariesDirectory)/perf-reports
      
      # FIX: Use $(Build.SourcesDirectory) to point exactly to your .jmx file
      jmeter -n -t $(Build.SourcesDirectory)/Performance-JMeter/performance.jmx -l $(Build.BinariesDirectory)/results.jtl -e -o $(Build.BinariesDirectory)/perf-reports
    displayName: 'Run JMeter Performance Test'
    continueOnError: true 

  # 3. PHASE 2: UNIFIED REPORTING & ARTIFACTS
  - task: PublishTestResults@2
    displayName: 'Publish Playwright Results'
    condition: succeededOrFailed() 
    inputs:
      testResultsFiles: '**/test-results/*.xml'
      testRunTitle: 'Playwright Combined Results'

  # This publishes the HTML Dashboard you saw locally to the Azure Pipeline UI
  - task: PublishBuildArtifacts@1
    displayName: 'Publish JMeter Performance Dashboard'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: '$(Build.BinariesDirectory)/perf-reports'
      ArtifactName: 'JMeter-Performance-Dashboard'
      publishLocation: 'Container'