trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  API_GROUPS: 'smoke'
  # It is highly recommended to store these in Azure DevOps Project Settings -> Variables
  # or in the Library (Variable Groups) as 'Secret' variables.
  LT_USERNAME: $(LT_USERNAME)
  LT_ACCESS_KEY: $(LT_ACCESS_KEY)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npx playwright install chromium --with-deps
    displayName: 'Install Playwright Browser'

  # 1. Run Playwright Tests TS
  - script: npx playwright test --config=Playwright-TS/Playwright-TS/
    displayName: 'Run Playwright TS Tests'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  # 2. Run JavaScript Single Test
  - script: npm run test:js
    displayName: 'Run Playwright JS Single Test'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  - script: npm run test:js-parallel
    displayName: 'Run Playwright JS Parallel Tests'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  # 3. PHASE: API TESTING (HYPEREXECUTE)
  # Orchestrate hybrid tests (Rest Assured + Selenium) via HyperExecute CLI
  - powershell: |
      # 1. Download HyperExecute CLI for Windows
      Invoke-WebRequest -Uri "https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe" -OutFile "hyperexecute.exe"
      
      # 2. Execute HyperExecute with your credentials and configuration
      # Using --user and --key ensures variables are passed correctly from Azure secrets.
      ./hyperexecute.exe --user $(LT_USERNAME) --key $(LT_ACCESS_KEY) --config API-RestAssured-hyper/hyperexecute.yaml
    displayName: 'Run HyperExecute Hybrid Tests'

  # 4. PHASE: JMETER PERFORMANCE TESTING
  - powershell: |
      choco install jmeter -y
      $env:Path += ";$env:JMETER_PATH"
      jmeter -version
    displayName: 'Install and Verify JMeter'

  - powershell: |
      New-Item -ItemType Directory -Force -Path $(Build.BinariesDirectory)/perf-reports
      jmeter -n -t $(Build.SourcesDirectory)/Performance-JMeter/performance.jmx -l $(Build.BinariesDirectory)/results.jtl -e -o $(Build.BinariesDirectory)/perf-reports
    displayName: 'Run JMeter Performance Test'
    continueOnError: true

  # 5. REPORTING & ARTIFACTS
  # Publishes standard JUnit results to the Azure Pipeline 'Tests' tab.
  - task: PublishTestResults@2
    displayName: 'Publish Combined Test Results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      # Searches for results generated by both local Playwright and HyperExecute nodes
      testResultsFiles: |
        **/test-results/*.xml
        **/surefire-reports/TEST-*.xml
      testRunTitle: 'Playwright & HyperExecute Results'

  # Uploads performance dashboards for manual review.
  - task: PublishBuildArtifacts@1
    displayName: 'Publish JMeter Performance Dashboard'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: '$(Build.BinariesDirectory)/perf-reports'
      ArtifactName: 'JMeter-Performance-Dashboard'
      publishLocation: 'Container'