trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  # Standard path for JMeter after Chocolatey installation
  JMETER_PATH: 'C:\ProgramData\chocolatey\bin'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npx playwright install chromium --with-deps
    displayName: 'Install Playwright Browser'

  # --- 1. RUN PLAYWRIGHT TESTS (TS & JS) ---
  - script: npx playwright test --config=Playwright-TS/Playwright-TS/
    displayName: 'Run Playwright TS Tests'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  - script: npm run test:js
    displayName: 'Run Playwright JS Single Test'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  - script: npm run test:js-parallel
    displayName: 'Run Playwright JS Parallel Tests'
    env:
      LT_USERNAME: $(LT_USERNAME)
      LT_ACCESS_KEY: $(LT_ACCESS_KEY)

  # --- 2. PHASE 2: JMETER PERFORMANCE TESTING ---
  - powershell: |
      choco install jmeter -y
      # Force update the PATH environment variable so the agent finds 'jmeter'
      $env:Path += ";$env:JMETER_PATH"
      jmeter -version
    displayName: 'Install and Verify JMeter'

  - powershell: |
      # Create clean directories for artifacts
      New-Item -ItemType Directory -Force -Path "$(Build.BinariesDirectory)\perf-reports"
      
      # FIX: Use absolute paths and ensure the file exists before running
      $jmxFile = "$(Build.SourcesDirectory)\Performance-JMeter\performance.jmx"
      if (Test-Path $jmxFile) {
          # Use quotation marks for paths with spaces to prevent 'Errorlevel 1'
          jmeter -n -t "$jmxFile" -l "$(Build.BinariesDirectory)\results.jtl" -e -o "$(Build.BinariesDirectory)\perf-reports"
      } else {
          Write-Error "ERROR: JMeter Test Plan not found at $jmxFile"
          exit 1
      }
    displayName: 'Run JMeter Performance Test'
    continueOnError: true 

  # --- 3. PHASE 2: UNIFIED REPORTING & ARTIFACTS ---
  - task: PublishTestResults@2
    displayName: 'Publish Playwright Results'
    condition: succeededOrFailed() 
    inputs:
      testResultsFiles: '**/test-results/*.xml'
      testRunTitle: 'Playwright Combined Results'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish JMeter Performance Dashboard'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: '$(Build.BinariesDirectory)\perf-reports'
      ArtifactName: 'JMeter-Performance-Dashboard'
      publishLocation: 'Container'