version: "0.1"
user: namratabtestmuai
key: '********'
testSuites: []
pre: ['mvn -Dmaven.repo.local=./.m2 dependency:resolve']
preDirectives:
    commands: ['mvn -Dmaven.repo.local=./.m2 dependency:resolve']
    maxRetries: 0
    shell: ""
    workingDirectory: ""
post: [mvn test -Dtest=postapi -DsuiteXmlFile=src/test/java/testing.xml]
postDirectives:
    commands: [mvn test -Dtest=postapi -DsuiteXmlFile=src/test/java/testing.xml]
    shell: ""
    workingDirectory: ""
jobLabel:
    - API_REST_ASSURED
    - SELENIUM
runson: win
autosplit: true
concurrency: 1
testDiscovery:
    command: grep 'class name' src/test/java/web.xml | awk -F'"' '{print $2}'
    mode: remote
    type: raw
testRunnerCommand: mvn test `-Dtest=$test `-Dbrowser=chrome `-Dversion=latest `-Dplatform="Windows 10" `-DsuiteXmlFile=src/test/java/web.xml
globalTimeout: 90
tunnelOpts:
    testsPerTunnel: 10
testSuiteTimeout: 90
testSuiteStep: 90
cacheDirectories:
    - $CACHE_DIR
cacheKey: '{{ checksum "pom.xml" }}'
retryOnFailure: true
maxRetries: 1
jobID: f6bed9ae-dffa-40d2-a783-bcfa7fe55881
mergeArtifacts: true
uploadArtefacts:
    - name: Report
      path:
        - target/surefire-reports/**
      email:
        to: []
        metaInfo: []
        linkValidity: 0
    - name: sessionjson
      path:
        - session.json
      email:
        to: []
        metaInfo: []
        linkValidity: 0
codeDirectory: API-RestAssured-hyper
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: null
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
        mitmProxy: false
        networkHar: false
        artifacts: false
        otherApps: []
        customData: {}
        smartUI: null
        darkMode: false
        testRemarks: false
        autoGrantPermissions: false
        networkLogsOptions:
            captureContent: false
            excludeHosts: []
            includeHosts: []
        enableResultBundle: false
        enableBluetooth: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
triggerSource: CLI
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: null
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: 01JZ03GE64ZZA2HBVGCPBNJ4FF
    name: LambdaTest Default Project
    type: custom
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
regionConfig:
    vm: []
    storage:
        region: ""
        enabled: false
        name: ""
        platform: azure
waitForArtefactsUpload: false
unzipPayload: false
projectpath: ""
accessibilityJob: false
globalPre:
    mode: ""
    commands: []
    maxRetries: 0
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
    cache: false
    yamlPath: null
    type: ""
    location: ""
globalPost:
    mode: ""
    commands: []
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
slackChannel: ""
whiteLabelProductTag: ""
sprofilePath: ""
ltOptions: {}
